import type { AppState } from '@/types'
import { addDays } from '@/engine/spaced-repetition/scheduling'

export const SEED: AppState = {
  contents: [
    {
      id: 'c1',
      title: 'Continuous Discovery Habits',
      type: 'book',
      author: 'Teresa Torres',
      desc: 'Processo contínuo de discovery para construir produtos que clientes amam.',
      addedAt: addDays(-15),
      progress: 65,
      color: '#7c3aed',
      trailId: null,
    },
    {
      id: 'c2',
      title: 'Prompt Engineering para PMs',
      type: 'course',
      author: 'Udemy',
      desc: 'Como usar IA generativa para acelerar o trabalho de Product Management.',
      addedAt: addDays(-5),
      progress: 30,
      color: '#06b6d4',
      trailId: null,
    },
    {
      id: 'c3',
      title: 'Inspired — Marty Cagan',
      type: 'book',
      author: 'Marty Cagan',
      desc: 'Como as melhores empresas de tech criam produtos que clientes adoram.',
      addedAt: addDays(-30),
      progress: 100,
      color: '#10b981',
      trailId: null,
    },
  ],
  cards: [
    {
      id: 'k1',
      cid: 'c1',
      front: 'O que é Opportunity Solution Tree?',
      back: 'Árvore visual que conecta o outcome desejado → oportunidades → soluções → experimentos de validação.',
      ef: 2.5,
      interval: 1,
      reps: 0,
      nextReview: new Date().toISOString(),
      lastReview: null,
      mastery: 'new',
    },
    {
      id: 'k2',
      cid: 'c1',
      front: 'Diferença entre output e outcome?',
      back: 'Output = o que você entrega (feature). Outcome = mudança de comportamento do usuário que gera valor ao negócio.',
      ef: 2.8,
      interval: 6,
      reps: 2,
      nextReview: addDays(-1),
      lastReview: addDays(-7),
      mastery: 'learning',
    },
    {
      id: 'k3',
      cid: 'c1',
      front: 'O que são Assumption Tests?',
      back: 'Experimentos rápidos e baratos para validar premissas arriscadas antes de construir. Ex: entrevistas, protótipos, fake door.',
      ef: 2.2,
      interval: 1,
      reps: 1,
      nextReview: new Date().toISOString(),
      lastReview: addDays(-2),
      mastery: 'learning',
    },
    {
      id: 'k4',
      cid: 'c2',
      front: 'O que é Chain-of-Thought prompting?',
      back: 'Instrui o modelo a "pensar passo a passo" antes de responder, melhorando raciocínio e qualidade de respostas complexas.',
      ef: 2.5,
      interval: 1,
      reps: 0,
      nextReview: new Date().toISOString(),
      lastReview: null,
      mastery: 'new',
    },
    {
      id: 'k5',
      cid: 'c3',
      front: '4 grandes riscos de produto (Cagan)?',
      back: '1. Valor — usuário quer?\n2. Usabilidade — consegue usar?\n3. Viabilidade — conseguimos construir?\n4. Negócio — funciona comercialmente?',
      ef: 3.2,
      interval: 21,
      reps: 4,
      nextReview: addDays(7),
      lastReview: addDays(-14),
      mastery: 'strong',
    },
    {
      id: 'k6',
      cid: 'c3',
      front: 'Discovery vs Delivery?',
      back: 'Discovery: encontrar a solução certa (validar). Delivery: executar e entregar com qualidade e velocidade.',
      ef: 3.0,
      interval: 14,
      reps: 3,
      nextReview: addDays(5),
      lastReview: addDays(-9),
      mastery: 'strong',
    },
  ],
  skills: [
    {
      id: 's1',
      name: 'Product Discovery',
      level: 3,
      xp: 340,
      maxXp: 500,
      cat: 'product',
      color: '#7c3aed',
    },
    {
      id: 's2',
      name: 'User Research',
      level: 2,
      xp: 180,
      maxXp: 300,
      cat: 'product',
      color: '#a78bfa',
    },
    {
      id: 's3',
      name: 'Prompt Engineering',
      level: 1,
      xp: 90,
      maxXp: 200,
      cat: 'tech',
      color: '#06b6d4',
    },
    {
      id: 's4',
      name: 'Product Strategy',
      level: 2,
      xp: 220,
      maxXp: 300,
      cat: 'product',
      color: '#10b981',
    },
    {
      id: 's5',
      name: 'Data Analysis',
      level: 1,
      xp: 60,
      maxXp: 200,
      cat: 'tech',
      color: '#f59e0b',
    },
    {
      id: 's6',
      name: 'Storytelling',
      level: 2,
      xp: 150,
      maxXp: 300,
      cat: 'soft',
      color: '#ec4899',
    },
  ],
  sessions: [],
  trails: [],
  streak: 5,
  lastStudyDate: new Date().toDateString(),
  totalXp: 1040,
  streakShields: 1,
}
